Merge Avantrip

diff --git a/dockdev b/dockdev
--- a/dockdev
+++ b/dockdev
@@ -22,7 +22,11 @@ export BASHX_DIR="$BASE_DIR/src/bashx"
 cd "$BASE_DIR"
 if [ ! -d "${BASHX_DIR}" ]; then
   echo "Installing BashX..."
-  git clone https://github.com/reduardo7/bashx.git "${BASHX_DIR}" || echo "Error installing BashX" && exit 1
+  if ! git clone https://github.com/reduardo7/bashx.git "${BASHX_DIR}"
+    then
+      echo "Error installing BashX"
+      exit 1
+    fi
 fi
 . "${BASHX_DIR}/src/bashx.sh"
 run "$@"
