Upgrade

diff --git a/dockdev b/dockdev
--- a/dockdev
+++ b/dockdev
@@ -1,13 +1,21 @@
 #!/bin/bash
 
-# ################### #
-#                     #
-# Application Manager #
-#                     #
-# ################### #
+############################################
+#                                          #
+# BashX                                    #
+#                                          #
+# Extended Bash Framework.                 #
+#                                          #
+# URL: https://github.com/reduardo7/bashx  #
+#                                          #
+# Author: Eduardo Daniel Cuomo             #
+#         eduardo.cuomo.ar@gmail.com       #
+#         reduardo7@gmail.com              #
+#                                          #
+############################################
 
 # BashX Required Version (INTEGER) | bashx.version
-BASHX_REQUIRED_VERSION=211
+BASHX_REQUIRED_VERSION=300
 
 BASE_SOURCE="$0"
 BASE_DIR="$(cd "$(dirname "$BASE_SOURCE")" ; pwd)"
@@ -20,40 +28,57 @@ export BASE_SOURCE="$BASE_SOURCE"
 export BASE_DIR="$BASE_DIR"
 export CURRENT_DIR="$(pwd)"
 export CURRENT_SOURCE="$CURRENT_DIR/$(basename "$0")"
-export CONFIG_FILE="$BASE_DIR/src/config.ini"
 export BASHX_DIR="$BASE_DIR/src/bashx"
-cd "$BASE_DIR"
+export BASHX_CURRENT_VERSION=`cat "${BASHX_DIR}/src/bashx.version" 2>/dev/null || echo 1`
 
-if [ ! -d "${BASHX_DIR}" ]; then
-  echo "# Installing BashX..."
-  if ! type git &>/dev/null
-    then
-      if ! sudo apt-get install git
-        then
-          echo "# Error installing GIT"
-          exit 1
-        fi
+# Running...
+(
+  _err() {
+    echo "# $@"
+    exit 1
+  }
+
+  _bxinstall() {
+    echo "# Installing BashX..."
+
+    if type wget &>/dev/null
+      then
+        wget --no-check-certificate https://github.com/reduardo7/bashx/tarball/v$BASHX_REQUIRED_VERSION -O - | tar -sxz || _err "Error downloading BashX"
+      else
+        if type curl &>/dev/null
+          then
+            curl -sL https://github.com/reduardo7/bashx/tarball/v$BASHX_REQUIRED_VERSION | tar -sxz || _err "Error downloading BashX"
+          else
+            echo "# WGET/cURL are not installed!"
+            echo "#"
+            echo "# Install WGET:"
+            echo "#     $ sudo apt-get install wget"
+            echo "# or cURL:"
+            echo "#     $ sudo apt-get install curl"
+            echo "#"
+            exit 1
+          fi
+      fi
+
+    mv reduardo7-bashx-* "${BASHX_DIR}" || _err "Error installing BashX"
+  }
+
+  cd "$BASE_DIR" || _err "Error"
+
+  if [ ! -d "${BASHX_DIR}" ]; then
+    _bxinstall
+  else
+    if [[ $BASHX_CURRENT_VERSION -lt $BASHX_REQUIRED_VERSION ]]; then
+      (
+        echo "# BashX requred version is v$BASHX_REQUIRED_VERSION, but version v$BASHX_CURRENT_VERSION is installed"
+        echo "# Updating BashX..."
+        rm -rf ${BASHX_DIR} || _err "Error removing old version"
+        _bxinstall || exit 1
+      )
     fi
-  if ! git clone https://github.com/reduardo7/bashx.git "${BASHX_DIR}"
-    then
-      echo "# Error installing BashX"
-      exit 1
-    fi
-else
-  BASHX_CURRENT_VERSION=`cat "${BASHX_DIR}/src/bashx.version" 2>/dev/null || echo 1`
-  if [[ $BASHX_CURRENT_VERSION -lt $BASHX_REQUIRED_VERSION ]]; then
-    (
-      echo "# BashX requred version is $BASHX_REQUIRED_VERSION, but version $BASHX_CURRENT_VERSION is installed"
-      echo "# Updating BashX..."
-      cd "${BASHX_DIR}"
-      if ! git pull
-        then
-          echo "# Error updating BashX"
-          exit 1
-        fi
-    )
   fi
-fi
 
-. "${BASHX_DIR}/src/bashx.sh"
-run "$@"
+  . "${BASHX_DIR}/src/bashx.sh"
+  @bxrun "$@"
+  exit $?
+)
