bashx upgrade v310

diff --git a/dockdev b/dockdev
--- a/dockdev
+++ b/dockdev
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 ############################################
 #                                          #
@@ -15,7 +15,12 @@
 ############################################
 
 # BashX Required Version (INTEGER) | bashx.version
-BASHX_REQUIRED_VERSION=300
+BASHX_REQUIRED_VERSION=310
+
+#export LC_CTYPE=en_US.UTF-8
+#export LC_ALL=en_US.UTF-8
+export LC_CTYPE=C
+export LC_ALL=C
 
 BASE_SOURCE="$0"
 BASE_DIR="$(cd "$(dirname "$BASE_SOURCE")" ; pwd)"
@@ -29,9 +34,9 @@ export BASE_DIR="$BASE_DIR"
 export CURRENT_DIR="$(pwd)"
 export CURRENT_SOURCE="$CURRENT_DIR/$(basename "$0")"
 export BASHX_DIR="$BASE_DIR/src/bashx"
-export BASHX_CURRENT_VERSION=`cat "${BASHX_DIR}/src/bashx.version" 2>/dev/null || echo 1`
+export BASHX_CURRENT_VERSION=$(cat "${BASHX_DIR}/src/bashx.version" 2>/dev/null || echo 1)
 
-# Running...
+# Install
 (
   _err() {
     echo "# $@"
@@ -41,13 +46,13 @@ export BASHX_CURRENT_VERSION=`cat "${BASHX_DIR}/src/bashx.version" 2>/dev/null |
   _bxinstall() {
     echo "# Installing BashX..."
 
-    if type wget &>/dev/null
+    if type wget >/dev/null 2>&1
       then
-        wget --no-check-certificate https://github.com/reduardo7/bashx/tarball/v$BASHX_REQUIRED_VERSION -O - | tar -sxz || _err "Error downloading BashX"
+        wget --no-check-certificate https://github.com/reduardo7/bashx/tarball/v${BASHX_REQUIRED_VERSION} -O - | tar -xz || _err "Error downloading BashX v${BASHX_REQUIRED_VERSION}"
       else
-        if type curl &>/dev/null
+        if type curl >/dev/null 2>&1
           then
-            curl -sL https://github.com/reduardo7/bashx/tarball/v$BASHX_REQUIRED_VERSION | tar -sxz || _err "Error downloading BashX"
+            curl -sL https://github.com/reduardo7/bashx/tarball/v${BASHX_REQUIRED_VERSION} | tar -xz || _err "Error downloading BashX v${BASHX_REQUIRED_VERSION}"
           else
             echo "# WGET/cURL are not installed!"
             echo "#"
@@ -70,15 +75,18 @@ export BASHX_CURRENT_VERSION=`cat "${BASHX_DIR}/src/bashx.version" 2>/dev/null |
   else
     if [[ $BASHX_CURRENT_VERSION -lt $BASHX_REQUIRED_VERSION ]]; then
       (
-        echo "# BashX requred version is v$BASHX_REQUIRED_VERSION, but version v$BASHX_CURRENT_VERSION is installed"
+        echo "# BashX requred version is v$BASHX_REQUIRED_VERSION, but version v${BASHX_CURRENT_VERSION} is installed"
         echo "# Updating BashX..."
         rm -rf ${BASHX_DIR} || _err "Error removing old version"
         _bxinstall || exit 1
       )
     fi
   fi
+)
 
+# Init
+(
   . "${BASHX_DIR}/src/bashx.sh"
-  @bxrun "$@"
+  @init "$@"
   exit $?
 )
